project:
  type: website
  output-dir: docs

website:
  title: "Home"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://robotneagu.github.io/STA9750-2025-FALL/"
  navbar:
      background: primary
      search: false
      left:
      - text: "Work"
        href: https://robotneagu.github.io/STA9750-2025-FALL/projects.html
      - text: "Resume"
        href: https://robotneagu.pythonanywhere.com
    
format:
  html:
    theme: cosmo
    toc: false

editor:
  mode: source